version: "3"

services: 
  nestjs_cors:
    build: .
    command: npm run start:dev
    ports: 
      - "3010:3000"
    volumes: 
      - .:/opt/docker_files/nestjs_cors
      - /opt/docker_files/nestjs_cors/node_modules